services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: gestion-candidatures-app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
